In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("data/customer_data.csv")
data.head()

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,multiple_lines,...,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,paperless_billing,payment_method,monthly_usage_gb,customer_service_calls,churn
0,1,42,Female,24,Month-to-month,74.35,1788.45,Fiber optic,Yes,Yes,...,No,Yes,No,Yes,Yes,Yes,Electronic check,215.3,1.0,No
1,2,28,Male,6,Month-to-month,60.15,371.85,Fiber optic,Yes,No,...,No,No,No,No,No,Yes,Electronic check,134.7,0.0,Yes
2,3,57,Male,36,One year,82.55,2927.85,Fiber optic,Yes,No,...,Yes,No,Yes,Yes,No,Yes,Credit card (automatic),187.2,0.0,No
3,4,35,Female,12,Month-to-month,55.25,671.75,DSL,Yes,No,...,No,No,No,No,No,No,Bank transfer (automatic),98.4,1.0,No
4,5,61,Female,58,Two year,92.85,5293.30,Fiber optic,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,Yes,Bank transfer (automatic),243.6,0.0,No

In [4]:
data.columns

Index(['customer_id', 'age', 'gender', 'tenure_months', 'contract_type',
       'monthly_charges', 'total_charges', 'internet_service', 'phone_service',
       'multiple_lines', 'online_security', 'online_backup',
       'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies',
       'paperless_billing', 'payment_method', 'monthly_usage_gb',
       'customer_service_calls', 'churn'],
      dtype='str')

In [14]:
data["tenure_months"] = data["tenure_months"].fillna(data["tenure_months"].mean())
data["monthly_charges"] = data["monthly_charges"].fillna(data["monthly_charges"].mean())
data["total_charges"] = data["total_charges"].fillna(data["total_charges"].mean())

In [15]:
data.head()

,customer_id,age,gender,tenure_months,contract_type,monthly_charges,total_charges,internet_service,phone_service,multiple_lines,...,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,paperless_billing,payment_method,monthly_usage_gb,customer_service_calls,churn
0,1,42,Female,24,Month-to-month,74.35,1788.45,Fiber optic,Yes,Yes,...,No,Yes,No,Yes,Yes,Yes,Electronic check,215.3,1.0,No
1,2,28,Male,6,Month-to-month,60.15,371.85,Fiber optic,Yes,No,...,No,No,No,No,No,Yes,Electronic check,134.7,0.0,Yes
2,3,57,Male,36,One year,82.55,2927.85,Fiber optic,Yes,No,...,Yes,No,Yes,Yes,No,Yes,Credit card (automatic),187.2,0.0,No
3,4,35,Female,12,Month-to-month,55.25,671.75,DSL,Yes,No,...,No,No,No,No,No,No,Bank transfer (automatic),98.4,1.0,No
4,5,61,Female,58,Two year,92.85,5293.30,Fiber optic,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,Yes,Bank transfer (automatic),243.6,0.0,No

In [ ]:
### Erlang C, Supongamos hay 100 agentes y el Shrinkage es del 30 porciento
# Entonces necesitariamos
# 100/(1-0.3)=143 agentes

# aht = total tiempo / llamadas atendidas


def erlang(transaction: int, aht: int) -> int:
    #TODO
    return 0

SyntaxError: invalid syntax (2426010035.py, line 2)